apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-172-17
  namespace: namespaceB
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 172.17.0.0/16
        except:
        - 172.17.1.0/24
    - namespaceSelector:
        matchLabels:
          myspace: namespaceA
    - podSelector:
        matchLabels:
          app: frontend
