---
- name: Install Nginx
  hosts: all
  remote_user: ubuntu
  become: true

  roles:
  - nginx
  
- name: Deploy Django application
  hosts: all
  remote_user: ubuntu
  become: true
  vars:
    django_secret_key: "{{ django_secret_key }}"
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
  
  roles:
  - django
